### ISSUE TITLE
Deleted Item in a Batch

### ISSUE THREAD

**Issue by michaelh18** [K3S/K3S-Replenish-Public#27]
My one PE Check had an item that was deleted after the batch was run and now I get this error when I get to the item:

![image](https://cloud.githubusercontent.com/assets/24811949/24562632/61047904-1619-11e7-925c-43febd08dcc2.png)

**Comment by kingharrison** [comment]
ok. Because the item no longer exists in batch I can do a few things and you can let me know what is best.

I could skip over the item completely to the next one. you wouldnt ever know it wasnt there though. 

I could show an 'item not found' screen and you click next. 

or I could kick out of the batch so you could start after it. 


thoughts?

**Comment by michaelh18** [comment]
I think skipping over it would be appropriate.   It would come up if we move an item from one vendor to another so we are already looking at the item or the item was discontinued and at that point we won’t care why it was in the batch.

[CBWblueBevelLogo]

Mike Hoffert
Category Manager
200 Lincoln West Drive
Mountville, PA 17554
717-285-8000 ext. 193
800-992-0592   Fax: 717-285-8008
Michael.Hoffert@cooperbooth.com<mailto:Michael.Hoffert@cooperbooth.com>
www.cooperbooth.com<http://www.cooperbooth.com/>

**Comment by kingharrison** [comment]
Makes sense to me. I like easy ones! Ill work on this next week..... or probably this weekend (who am I kidding, hah!) Have a great weekend Mike!

**Comment by kingharrison** [comment]
So this one is a bit tougher to fix because conceptually I understand it, but to find it on ours where the condition doesnt exist has been hard. 

SO

I have put in a message that should capture the state that cause the error. You will get a white screen that says to email me a screenshot. If we can get that to work I can fix the error next round. 

This will go in tomorrow in version 4.4.17

**Comment by kingharrison** [comment]
Ok I believe we have this tracked down and a way to tackle this. Should have a fix for this soon.

**Comment by kingharrison** [comment]
This is fixed in the next update.
