### ISSUE TITLE
Approved Purchase Orders for Product - Incorrect Data

### ISSUE THREAD

**Issue by ajschenk** [K3S/K3S-Replenish-Public#3]
Looking at "Product POs" for item# 201178, several columns are displaying incorrect data.

PO Number: Correct
Ordered: Correct
Expected Arrival Date: correct, with the exception of the top two rows (no date)
Expected LT: incorrect - showing expected arrival date instead of LT calculation
Actual Received: incorrect - showing PO number instead of actual date of receipt
Actual LT: incorrect - showing PO number instead of actual calculated LT
Received: looks correct at this point
Ordered: top two rows are blank, and should show the qty ordered on those respective POs

URL: http://10.5.49.15:8051/orders/productpoindex?ID_LOCN=1&IB_SUPL=013030&IB_SUPLSUB=&ID_PROD=201178

![image](https://cloud.githubusercontent.com/assets/22618097/19189705/71863efc-8c67-11e6-8c5f-592163a40051.png)

**Comment by kingharrison** [comment]
Could you attach a Jelly Bean screen of the correct as well?

**Comment by ajschenk** [comment]
![image](https://cloud.githubusercontent.com/assets/22618097/19198471/50edeac0-8c8d-11e6-84a0-4290fcd0144f.png)

**Comment by kingharrison** [comment]
@UserInHIsName I am going to need your help with this one because it looks like the fields come from a couple different files and / or are calculated and my first stab at it was off. 

The green screen version is K3S_1045. 

I believe I get some of these values from joining K_INTORDB and K_INTORDB. Maybe including K_SUPLIER?

Purchase Order # - ID_PO# & IB_PO#
Ordered - 
Expected Arrival - Is this calculated from the K_SUPLIER.SP_LEADTMQ field added onto when Ordered?
Expected Lead Time - Is this pulled from K_SUPLIER? SP_LEADTMQ?
Actual 1st Received - IB_ARRIVE?
1st Lead Time - ?? I can't tell where this comes from
Total Quantity Received - ?? Not sure
Quantity Ordered - ID_SOQACT

**Comment by kingharrison** [comment]
I believe this is now fixed. Please inspect. Version 10.15.16
