### ISSUE TITLE
Fixed Order Cycle

### ISSUE THREAD

**Issue by michaelh18** [K3S/K3S-Replenish-Public#32]
For some vendors (153216 and 154690 I know for sure) the Fixed Order Cycle doesn't open properly.  Instead you get the image below.

![image](https://user-images.githubusercontent.com/24811949/27226294-414ab1a2-526c-11e7-8aad-810b2aad4cda.png)

**Comment by kingharrison** [comment]
Working on that. Want to provide a warning that the order cycle isn't used for fixed cycle, but you can still play with the numbers.

We have a very large update coming soon fixing a lot of things. It's taking a minute because we're trying to make sure it works correct. Didn't want you to think we're ignoring your support issues on here.

-King Harrison
Sent from iPhone
Please excuse all typos
________________________________

**Comment by michaelh18** [comment]
I did not mean Order cycle.  It’s the Fixed Cycle.  Those are both fixed Cycle vendors.  I’m not trying to adjust the order cycle for them, I’m clicking on Fixed Cycle to get the screen below.

[CBWblueBevelLogo]

Mike Hoffert
Category Manager
200 Lincoln West Drive
Mountville, PA 17554
717-285-8000 ext. 193
800-992-0592   Fax: 717-285-8008
Michael.Hoffert@cooperbooth.com<mailto:Michael.Hoffert@cooperbooth.com>
www.cooperbooth.com<http://www.cooperbooth.com/>

**Comment by kingharrison** [comment]
Gotcha. I will look into it

-King Harrison
Sent from iPhone
Please excuse all typos
________________________________

**Comment by kingharrison** [comment]
Found the bug. It was actually from the ' in Nathan's. It will be fixed in the next update. Should be soon.

**Comment by michaelh18** [comment]
That explains why it didn’t work for “Bozzuto’s” either.

[CBWblueBevelLogo]

Mike Hoffert
Category Manager
200 Lincoln West Drive
Mountville, PA 17554
717-285-8000 ext. 193
800-992-0592   Fax: 717-285-8008
Michael.Hoffert@cooperbooth.com<mailto:Michael.Hoffert@cooperbooth.com>
www.cooperbooth.com<http://www.cooperbooth.com/>

**Comment by kingharrison** [comment]
Yes. and it wasn't just the Fixed cycle button. All the features of that screen were off.
