### ISSUE TITLE
Vendor 155809 Manual item adjustment zero's SOQ

### ISSUE THREAD

**Issue by michaelh18** [K3S/K3S-Replenish-Public#37]
When I manually adjust an manual item in vendor 155809 and only in vendor 155809, the SOQ is reduced to 0.

![image](https://user-images.githubusercontent.com/24811949/31019457-bde3e0ce-a4fd-11e7-91b6-e9a4108d3db0.png)
 and I get the following error when I try to approve the order.

![image](https://user-images.githubusercontent.com/24811949/31019479-d0aa93ce-a4fd-11e7-969b-2c72a653e718.png)

**Comment by kingharrison** [comment]
I will look at that right now.


On September 29, 2017 at 10:06:41 AM, michaelh18 (notifications@github.com)
wrote:

When I manually adjust an manual item in vendor 155809 and only in vendor
155809, the SOQ is reduced to 0.

[image: image]
<https://user-images.githubusercontent.com/24811949/31019457-bde3e0ce-a4fd-11e7-91b6-e9a4108d3db0.png>
and I get the following error when I try to approve the order.

[image: image]
<https://user-images.githubusercontent.com/24811949/31019479-d0aa93ce-a4fd-11e7-969b-2c72a653e718.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/K3S/K3S-Replenish-Public/issues/37>, or mute the thread

**Comment by kingharrison** [comment]
We were able to replicate it and it happens when you adjust product in that supplier. Working on it now.

**Comment by kingharrison** [comment]
Hey @michaelh18 we were finally able to identify the issue. It will be pushed out by Monday. This one was difficult to find the exact cause but we got it!
